name: edX CI/CD Pipeline 2

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('docker-compose.yml', 'requirements/**') }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build MySQL service
      run: |
        docker-compose -f docker-compose.yml.mysqldbdump up --build --no-start mysql

    - name: Build edxapp service
      run: |
        docker-compose -f docker-compose.yml.mysqldbdump up --build --no-start edxapp

    - name: Start MySQL service
      run: |
        docker-compose -f docker-compose.yml.mysqldbdump start mysql

    - name: Wait for MySQL to initialize
      run: |
        docker-compose -f docker-compose.yml.mysqldump wait mysql

    - name: Run edX platform setup
      run: |
        docker-compose -f docker-compose.yml.mysqldbdump run edxapp bash -c '
          source /edx/app/edxapp/edxapp_env && 
          cd /edx/app/edxapp/edx-platform/ && 
          paver update_db
        '

    - name: Install project dependencies
      run: |
        docker-compose -f docker-compose.yml.mysqldbdump run edxapp bash -c '
          source /edx/app/edxapp/edxapp_env && 
          cd /edx/app/edxapp/edx-platform/ && 
          make requirements
